/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsultantIndexRouteImport } from './routes/consultant/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCreateUserRouteImport } from './routes/admin/create-user'
import { Route as ClientLandIndexRouteImport } from './routes/client/land/index'
import { Route as ClientLandCreateRouteImport } from './routes/client/land/create'
import { Route as AdminUpdateUserIdRouteImport } from './routes/admin/update-user.$id'
import { Route as ClientLandIdIndexRouteImport } from './routes/client/land/$id/index'
import { Route as ClientLandUpdateIdRouteImport } from './routes/client/land/update.$id'
import { Route as ClientLandIdSensorIndexRouteImport } from './routes/client/land/$id/sensor/index'
import { Route as ClientLandIdSensorCreateRouteImport } from './routes/client/land/$id/sensor/create'
import { Route as ClientLandIdSensorUpdateIdRouteImport } from './routes/client/land/$id/sensor/update.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantIndexRoute = ConsultantIndexRouteImport.update({
  id: '/consultant/',
  path: '/consultant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateUserRoute = AdminCreateUserRouteImport.update({
  id: '/admin/create-user',
  path: '/admin/create-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLandIndexRoute = ClientLandIndexRouteImport.update({
  id: '/client/land/',
  path: '/client/land/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLandCreateRoute = ClientLandCreateRouteImport.update({
  id: '/client/land/create',
  path: '/client/land/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdateUserIdRoute = AdminUpdateUserIdRouteImport.update({
  id: '/admin/update-user/$id',
  path: '/admin/update-user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLandIdIndexRoute = ClientLandIdIndexRouteImport.update({
  id: '/client/land/$id/',
  path: '/client/land/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLandUpdateIdRoute = ClientLandUpdateIdRouteImport.update({
  id: '/client/land/update/$id',
  path: '/client/land/update/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLandIdSensorIndexRoute = ClientLandIdSensorIndexRouteImport.update({
  id: '/client/land/$id/sensor/',
  path: '/client/land/$id/sensor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLandIdSensorCreateRoute =
  ClientLandIdSensorCreateRouteImport.update({
    id: '/client/land/$id/sensor/create',
    path: '/client/land/$id/sensor/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientLandIdSensorUpdateIdRoute =
  ClientLandIdSensorUpdateIdRouteImport.update({
    id: '/client/land/$id/sensor/update/$id',
    path: '/client/land/$id/sensor/update/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin': typeof AdminIndexRoute
  '/consultant': typeof ConsultantIndexRoute
  '/admin/update-user/$id': typeof AdminUpdateUserIdRoute
  '/client/land/create': typeof ClientLandCreateRoute
  '/client/land': typeof ClientLandIndexRoute
  '/client/land/update/$id': typeof ClientLandUpdateIdRoute
  '/client/land/$id': typeof ClientLandIdIndexRoute
  '/client/land/$id/sensor/create': typeof ClientLandIdSensorCreateRoute
  '/client/land/$id/sensor': typeof ClientLandIdSensorIndexRoute
  '/client/land/$id/sensor/update/$id': typeof ClientLandIdSensorUpdateIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin': typeof AdminIndexRoute
  '/consultant': typeof ConsultantIndexRoute
  '/admin/update-user/$id': typeof AdminUpdateUserIdRoute
  '/client/land/create': typeof ClientLandCreateRoute
  '/client/land': typeof ClientLandIndexRoute
  '/client/land/update/$id': typeof ClientLandUpdateIdRoute
  '/client/land/$id': typeof ClientLandIdIndexRoute
  '/client/land/$id/sensor/create': typeof ClientLandIdSensorCreateRoute
  '/client/land/$id/sensor': typeof ClientLandIdSensorIndexRoute
  '/client/land/$id/sensor/update/$id': typeof ClientLandIdSensorUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/admin/create-user': typeof AdminCreateUserRoute
  '/admin/': typeof AdminIndexRoute
  '/consultant/': typeof ConsultantIndexRoute
  '/admin/update-user/$id': typeof AdminUpdateUserIdRoute
  '/client/land/create': typeof ClientLandCreateRoute
  '/client/land/': typeof ClientLandIndexRoute
  '/client/land/update/$id': typeof ClientLandUpdateIdRoute
  '/client/land/$id/': typeof ClientLandIdIndexRoute
  '/client/land/$id/sensor/create': typeof ClientLandIdSensorCreateRoute
  '/client/land/$id/sensor/': typeof ClientLandIdSensorIndexRoute
  '/client/land/$id/sensor/update/$id': typeof ClientLandIdSensorUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/admin/create-user'
    | '/admin'
    | '/consultant'
    | '/admin/update-user/$id'
    | '/client/land/create'
    | '/client/land'
    | '/client/land/update/$id'
    | '/client/land/$id'
    | '/client/land/$id/sensor/create'
    | '/client/land/$id/sensor'
    | '/client/land/$id/sensor/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin/create-user'
    | '/admin'
    | '/consultant'
    | '/admin/update-user/$id'
    | '/client/land/create'
    | '/client/land'
    | '/client/land/update/$id'
    | '/client/land/$id'
    | '/client/land/$id/sensor/create'
    | '/client/land/$id/sensor'
    | '/client/land/$id/sensor/update/$id'
  id:
    | '__root__'
    | '/login'
    | '/admin/create-user'
    | '/admin/'
    | '/consultant/'
    | '/admin/update-user/$id'
    | '/client/land/create'
    | '/client/land/'
    | '/client/land/update/$id'
    | '/client/land/$id/'
    | '/client/land/$id/sensor/create'
    | '/client/land/$id/sensor/'
    | '/client/land/$id/sensor/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  AdminCreateUserRoute: typeof AdminCreateUserRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ConsultantIndexRoute: typeof ConsultantIndexRoute
  AdminUpdateUserIdRoute: typeof AdminUpdateUserIdRoute
  ClientLandCreateRoute: typeof ClientLandCreateRoute
  ClientLandIndexRoute: typeof ClientLandIndexRoute
  ClientLandUpdateIdRoute: typeof ClientLandUpdateIdRoute
  ClientLandIdIndexRoute: typeof ClientLandIdIndexRoute
  ClientLandIdSensorCreateRoute: typeof ClientLandIdSensorCreateRoute
  ClientLandIdSensorIndexRoute: typeof ClientLandIdSensorIndexRoute
  ClientLandIdSensorUpdateIdRoute: typeof ClientLandIdSensorUpdateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultant/': {
      id: '/consultant/'
      path: '/consultant'
      fullPath: '/consultant'
      preLoaderRoute: typeof ConsultantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-user': {
      id: '/admin/create-user'
      path: '/admin/create-user'
      fullPath: '/admin/create-user'
      preLoaderRoute: typeof AdminCreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/': {
      id: '/client/land/'
      path: '/client/land'
      fullPath: '/client/land'
      preLoaderRoute: typeof ClientLandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/create': {
      id: '/client/land/create'
      path: '/client/land/create'
      fullPath: '/client/land/create'
      preLoaderRoute: typeof ClientLandCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/update-user/$id': {
      id: '/admin/update-user/$id'
      path: '/admin/update-user/$id'
      fullPath: '/admin/update-user/$id'
      preLoaderRoute: typeof AdminUpdateUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$id/': {
      id: '/client/land/$id/'
      path: '/client/land/$id'
      fullPath: '/client/land/$id'
      preLoaderRoute: typeof ClientLandIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/update/$id': {
      id: '/client/land/update/$id'
      path: '/client/land/update/$id'
      fullPath: '/client/land/update/$id'
      preLoaderRoute: typeof ClientLandUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$id/sensor/': {
      id: '/client/land/$id/sensor/'
      path: '/client/land/$id/sensor'
      fullPath: '/client/land/$id/sensor'
      preLoaderRoute: typeof ClientLandIdSensorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$id/sensor/create': {
      id: '/client/land/$id/sensor/create'
      path: '/client/land/$id/sensor/create'
      fullPath: '/client/land/$id/sensor/create'
      preLoaderRoute: typeof ClientLandIdSensorCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/land/$id/sensor/update/$id': {
      id: '/client/land/$id/sensor/update/$id'
      path: '/client/land/$id/sensor/update/$id'
      fullPath: '/client/land/$id/sensor/update/$id'
      preLoaderRoute: typeof ClientLandIdSensorUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  AdminCreateUserRoute: AdminCreateUserRoute,
  AdminIndexRoute: AdminIndexRoute,
  ConsultantIndexRoute: ConsultantIndexRoute,
  AdminUpdateUserIdRoute: AdminUpdateUserIdRoute,
  ClientLandCreateRoute: ClientLandCreateRoute,
  ClientLandIndexRoute: ClientLandIndexRoute,
  ClientLandUpdateIdRoute: ClientLandUpdateIdRoute,
  ClientLandIdIndexRoute: ClientLandIdIndexRoute,
  ClientLandIdSensorCreateRoute: ClientLandIdSensorCreateRoute,
  ClientLandIdSensorIndexRoute: ClientLandIdSensorIndexRoute,
  ClientLandIdSensorUpdateIdRoute: ClientLandIdSensorUpdateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
